# .github/workflows/deploy.yml
name: CI/CD build & deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build fat JAR
        run: ./mvnw clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/p3-orchestrator:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/p3-orchestrator:latest

  deploy:
    name: SSH & restart on EC2
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - name: Deploy & restart container
        uses: appleboy/ssh-action@v0.1.6
        with:
          host:     ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key:      ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -eux
            # stop & remove old
            docker stop p3-orchestrator-app || true
            docker rm   p3-orchestrator-app || true

            # pull latest from Docker Hub
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/p3-orchestrator:latest

            # run it (with Docker socket & logs volume)
            docker run -d \
              --name p3-orchestrator-app \
              -p 8080:8080 \
              -v /var/run/docker.sock:/var/run/docker.sock \
              -v /home/ubuntu/p3-logs:/app/logs \
              ${{ secrets.DOCKERHUB_USERNAME }}/p3-orchestrator:latest
